CREATE TABLE NHACUNGCAP(
    MaNhaCC varchar(20) PRIMARY KEY,
    TenNhaCC NVARCHAR(255) NOT NULL,
    DiaChi text NOT NULL,
    SoDT VARCHAR(15) NOT NULL,
    MaSoThue VARCHAR(20) 
);

CREATE TABLE LOAIDICHVU(
    MaLoaiDV varchar(20) PRIMARY KEY,
    TenLoaiDv NVARCHAR(255) NOT NULL
);

CREATE TABLE DongXe(
    DongXe NVARCHAR(255) PRIMARY KEY,
    HangXe VARCHAR(20) NOT NULL,
    SoChoNgoi int NOT NULL 
);

CREATE TABLE MUCPHI(
    MaMP VARCHAR(20) PRIMARY KEY,
    DonGia DECIMAL(12,4) NOT NULL CHECK(DonGia>=0) DEFAULT 0,
    MoTa NTEXT NOT NULL
);

CREATE TABLE DANGKYCUNGCAP(
    MaDKCC VARCHAR(20) PRIMARY KEY,
    MaNhaCC VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES NHACUNGCAP(MaNhaCC),
    MaLoaiDv VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES LOAIDICHVU(MaLoaiDV),
    DongXe NVARCHAR(255) NOT NULL FOREIGN KEY REFERENCES DONGXE(DongXe),
    MaMP VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES MUCPHI(MaMP),
    NgatBatDauCungCap DATE NOT NULL,
    NgayKetThucCungCap DATE NOT NULL,
    SoLuongXeDangKy INT NOT NULL CHECK (SoLuongXeDangKy>0)
);